# Generated by Django 5.1.4 on 2025-05-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="history",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="result",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("img", models.ImageField(upload_to="images/")),
                ("text", models.TextField(blank=True, null=True)),
                ("primary_factor", models.CharField(max_length=100)),
                ("visual_feature", models.FloatField(blank=True, null=True)),
                ("semantic_feature", models.FloatField(blank=True, null=True)),
                ("combined_feature", models.FloatField(blank=True, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "result",
                    models.IntegerField(
                        choices=[
                            (1, "Unknown"),
                            (2, "Perjudian"),
                            (3, "Bukan Perjudian"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "history_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="detectionapp.history",
                    ),
                ),
            ],
        ),
    ]
